# syntax=docker/dockerfile:1-labs@sha256:7eca9451d94f9b8ad22e44988b92d595d3e4d65163794237949a8c3413fbed5d

ARG NODE_VERSION=22.18.0

FROM node:${NODE_VERSION}-bookworm-slim

ARG GHOST_BUILD_VERSION=""
ENV NODE_ENV=production
ENV GHOST_BUILD_VERSION=${GHOST_BUILD_VERSION}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libjemalloc2 \
    fontconfig \
    build-essential \
    python3 && \
    rm -rf /var/lib/apt/lists/*

RUN groupmod -g 1001 node && \
    usermod -u 1001 node && \
    adduser --disabled-password --gecos "" -u 1000 ghost

WORKDIR /home/ghost

COPY . .

RUN corepack enable

ENV HUSKY=0
ENV CI=true

RUN --mount=type=cache,target=/root/.local/share/pnpm/store,id=pnpm-store \
    pnpm install --prod --prefer-offline --ignore-scripts

RUN mkdir -p /home/ghost/content/data && \
    mkdir -p /home/ghost/content/logs && \
    mkdir -p /home/ghost/default && \
    mkdir -p /home/ghost/log && \
    cp -R content base_content && \
    cp -R content/themes/casper default/casper && \
    ([ -d content/themes/source ] && cp -R content/themes/source default/source || true) && \
    chown ghost:ghost /home/ghost && \
    chown -R nobody:nogroup /home/ghost/* && \
    chown -R ghost:ghost /home/ghost/content /home/ghost/log

USER ghost

ENV LD_PRELOAD=libjemalloc.so.2
ENV database__client=sqlite3
ENV database_connection_filename=/home/ghost/content/data/ghost.db

EXPOSE 2368

CMD ["node", "index.js"]
