global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:

  # =====================================
  # PROMETHEUS SELF MONITORING
  # =====================================
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # =====================================
  # GHOST APPLICATION
  # =====================================
  - job_name: "ghost"
    static_configs:
      - targets: ["ghost-app:2368"]

  # =====================================
  # NODE EXPORTER (OPTIONAL)
  # =====================================
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
