# File: kubernetes/ghost-deployment.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: ghost

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app
  namespace: ghost

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ghost

  template:
    metadata:
      labels:
        app: ghost

    spec:
      containers:
        - name: ghost
          image: ghost:5-alpine
          imagePullPolicy: Always

          ports:
            - containerPort: 2368

          env:
            - name: url
              value: "http://localhost:30007"

            - name: NODE_ENV
              value: "development"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 60
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 40
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost

spec:
  type: NodePort

  selector:
    app: ghost

  ports:
    - protocol: TCP
      port: 2368
      targetPort: 2368
      nodePort: 30007

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ghost-hpa
  namespace: ghost

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost-app

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70