apiVersion: v1
kind: Namespace
metadata:
  name: ghost

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 3

  selector:
    matchLabels:
      app: ghost

  template:
    metadata:
      labels:
        app: ghost

    spec:
      containers:
        - name: ghost

          image: nileshrajurwar9403/ghost-app:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 2368

          env:
            - name: url
              value: "http://ghost.yourdomain.com"

            - name: NODE_ENV
              value: "production"

            - name: database__client
              value: "sqlite3"

            - name: database__connection__filename
              value: "/home/ghost/content/data/ghost.db"

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 20
            periodSeconds: 5

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ghost-hpa
  namespace: ghost

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
